FROM node:lts-alpine3.19 AS build

WORKDIR /app
COPY . .
RUN npm install
RUN npm run build

FROM nginx:latest
WORKDIR /usr/share/nginx/html
RUN rm -rf ./*
COPY --from=build /app/dist .

ENV VITE_BASE_URL="http://localhost:8000/api"

ENTRYPOINT [ "nginx","-g", "daemon off;" ]
